# Experiment constants
ROUNDS_PER_PHASE = 25
SAFE_PROB_INIT = 0.5
UNCERTAIN_PROB_MIN = 0.2
UNCERTAIN_PROB_MAX = 0.8
PROB_ADJUST = 0.02
PROB_LIMIT_MIN = 0.3
PROB_LIMIT_MAX = 0.7
REWARD_RED = 5
REWARD_BLACK = -2
REWARD_GOLD = 20
REWARD_SILVER = -10
RUMSFELD_SPECIAL_PROB_PHASE2 = 0.10
RUMSFELD_SPECIAL_PROB_PHASE3 = 0.15
DATA_FILE = 'experiment_data.csv'
PHASES = [1, 2, 3]
